export default {
  TYPE: "TYPE",
  CLEAR: "CLEAR",
  SIGN: "SIGN",
  DELETE: "DELETE",
  SET: "SET",
  ADD_DIVIDER: "ADD_DIVIDER",
  REMOVE_DIVIDER: "REMOVE_DIVIDER",
  ADD_TO_DIVIDER: "ADD_TO_DIVIDER",
  SELECT_DIVIDER: "SELECT_DIVIDER",
  REMOVE_SELECTION: "REMOVE_SELECTION",
  PUSH_STATE: "PUSH_STATE",
  POP_STATE: "POP_STATE",
  SET_STATE: "SET_STATE"
};

export const emitterActionNames = {
  CLEAR_CALC: "CLEAR_CALC"
};
