export default {
  TYPE: "TYPE",
  CLEAR: "CLEAR",
  SIGN: "SIGN",
  DELETE: "DELETE",
  SAVE: "SAVE",
  NEW_OPERATOR: "NEW_OPERATOR",
  RESOLVE: "RESOLVE",
  CLEAR_MAIN: "CLEAR_MAIN",
  CLEAR_SAVED: "CLEAR_SAVED",
  CLEAR_OPERATOR: "CLEAR_OPERATOR"
};
